### ISSUE TITLE
[Meta] PR 的预览存在问题

### ISSUE THREAD

**Issue by SeraphJACK** [TeamCovertDragon/Sputnik#16]
见 #15 的预览。VuePress 生成的静态页面所加载的资源路径前都有 `/` ，导致预览时所有静态资源无法加载。

**Comment by SeraphJACK** [comment]
所有的链接也有同样的问题

**Comment by Yesterday17** [comment]
~~设置 `--base` 即可。~~
配置文件设置 `base` 即可

https://vuepress.vuejs.org/config/#base

**Comment by 3TUSK** [comment]
Vuepress 支持通过 CLI 覆盖 `.vuepress/config.js` 里的配置？

**Comment by Yesterday17** [comment]
@3TUSK 不行 我之前看到 `config` 和 `cli` 都有 `dest` 以为是支持的

**Comment by SeraphJACK** [comment]
~~等一波 vuejs/vuepress#796~~

草这 issue 都开了两年了

**Comment by 3TUSK** [comment]
所以我们得想个办法在构建时换掉 `.vuepress/config.js`。直接 `sed 's/base: "\/"/base: "\/${pr_num}\/"/g`？

**Comment by jihuayu** [comment]
众所周知config.js是js，可以用获取环境变量
![image](https://user-images.githubusercontent.com/32858525/77843719-8fed8400-71d2-11ea-84f0-664e2b9d8329.png)

**Comment by SeraphJACK** [comment]
那我发个 pr 关这个 issue 吧（
