### ISSUE TITLE
[NewContent] 事件概述

### ISSUE THREAD

**Issue by SeraphJACK** [TeamCovertDragon/Sputnik#8]

**Comment by switefaster** [comment]
我觉得事件概述应该重点介绍一下事件模型，提一下 @SubscribeEvent 和 @EventBusSubscriber 的作用和MinecraftForge.EVENT_BUS 就行了。不然入口不讲生命周期事件都没什么好写的东西了……

**Comment by 3TUSK** [comment]
以及 `FMLJavaModLoadingContext.get().getModEventBus()`。

**Comment by switefaster** [comment]
这个我在入口里面提到了，不过无妨。
